<?php

declare(strict_types=1);

return [
    'CREATE TABLE IF NOT EXISTS recruiter_profiles (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        user_id BIGINT UNSIGNED NOT NULL UNIQUE,
        company_name VARCHAR(180) NULL,
        company_email VARCHAR(255) NULL,
        company_phone VARCHAR(30) NULL,
        company_website VARCHAR(255) NULL,
        industry VARCHAR(120) NULL,
        company_size VARCHAR(80) NULL,
        rc_number VARCHAR(100) NULL,
        address TEXT NULL,
        verification_status ENUM("pending", "under_review", "verified", "rejected", "suspended") NOT NULL DEFAULT "pending",
        verified_at TIMESTAMP NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_recruiter_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        INDEX idx_recruiter_profiles_user_id (user_id),
        INDEX idx_recruiter_profiles_verification_status (verification_status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS recruiter_documents (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        recruiter_id BIGINT UNSIGNED NOT NULL,
        document_type VARCHAR(100) NOT NULL,
        file_path VARCHAR(255) NOT NULL,
        status ENUM("pending", "approved", "rejected") NOT NULL DEFAULT "pending",
        reviewed_by BIGINT UNSIGNED NULL,
        reviewed_at TIMESTAMP NULL,
        rejection_reason TEXT NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_recruiter_documents_recruiter FOREIGN KEY (recruiter_id) REFERENCES recruiter_profiles(id) ON DELETE CASCADE,
        CONSTRAINT fk_recruiter_documents_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
        INDEX idx_recruiter_documents_recruiter_id (recruiter_id),
        INDEX idx_recruiter_documents_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS hr_officer_profiles (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        user_id BIGINT UNSIGNED NOT NULL UNIQUE,
        employee_code VARCHAR(80) NULL UNIQUE,
        referral_code VARCHAR(80) NULL UNIQUE,
        performance_score DECIMAL(5,2) NOT NULL DEFAULT 0,
        active_candidate_count INT UNSIGNED NOT NULL DEFAULT 0,
        successful_placements_count INT UNSIGNED NOT NULL DEFAULT 0,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_hr_officer_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS relationship_officer_profiles (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        user_id BIGINT UNSIGNED NOT NULL UNIQUE,
        employee_code VARCHAR(80) NULL UNIQUE,
        assigned_employer_count INT UNSIGNED NOT NULL DEFAULT 0,
        assigned_job_count INT UNSIGNED NOT NULL DEFAULT 0,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_relationship_officer_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS job_seeker_profiles (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        user_id BIGINT UNSIGNED NOT NULL UNIQUE,
        profile_code VARCHAR(80) NULL UNIQUE,
        gender VARCHAR(30) NULL,
        date_of_birth DATE NULL,
        location VARCHAR(150) NULL,
        current_job_title VARCHAR(150) NULL,
        years_of_experience DECIMAL(4,1) NULL,
        salary_expectation_min DECIMAL(14,2) NULL,
        salary_expectation_max DECIMAL(14,2) NULL,
        availability_status VARCHAR(80) NULL,
        profile_completion_percentage TINYINT UNSIGNED NOT NULL DEFAULT 0,
        assigned_hr_officer_id BIGINT UNSIGNED NULL,
        referred_by_hr_officer_id BIGINT UNSIGNED NULL,
        onboarding_status ENUM("pending", "in_progress", "completed") NOT NULL DEFAULT "pending",
        completed_steps_json JSON NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_job_seeker_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT fk_job_seeker_profiles_assigned_hr FOREIGN KEY (assigned_hr_officer_id) REFERENCES users(id) ON DELETE SET NULL,
        CONSTRAINT fk_job_seeker_profiles_referred_hr FOREIGN KEY (referred_by_hr_officer_id) REFERENCES users(id) ON DELETE SET NULL,
        INDEX idx_job_seeker_profiles_user_id (user_id),
        INDEX idx_job_seeker_profiles_assigned_hr (assigned_hr_officer_id),
        INDEX idx_job_seeker_profiles_location (location)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS job_seeker_skills (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        job_seeker_id BIGINT UNSIGNED NOT NULL,
        skill_name VARCHAR(120) NOT NULL,
        proficiency_level VARCHAR(80) NULL,
        created_at TIMESTAMP NULL,
        CONSTRAINT fk_job_seeker_skills_profile FOREIGN KEY (job_seeker_id) REFERENCES job_seeker_profiles(id) ON DELETE CASCADE,
        INDEX idx_job_seeker_skills_profile (job_seeker_id),
        INDEX idx_job_seeker_skills_name (skill_name)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS job_seeker_work_experiences (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        job_seeker_id BIGINT UNSIGNED NOT NULL,
        company_name VARCHAR(180) NOT NULL,
        job_title VARCHAR(180) NOT NULL,
        start_date DATE NULL,
        end_date DATE NULL,
        is_current TINYINT(1) NOT NULL DEFAULT 0,
        description TEXT NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_job_seeker_work_profile FOREIGN KEY (job_seeker_id) REFERENCES job_seeker_profiles(id) ON DELETE CASCADE,
        INDEX idx_job_seeker_work_profile (job_seeker_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS job_seeker_educations (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        job_seeker_id BIGINT UNSIGNED NOT NULL,
        institution VARCHAR(180) NOT NULL,
        qualification VARCHAR(150) NOT NULL,
        field_of_study VARCHAR(150) NULL,
        start_year SMALLINT UNSIGNED NULL,
        end_year SMALLINT UNSIGNED NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_job_seeker_educations_profile FOREIGN KEY (job_seeker_id) REFERENCES job_seeker_profiles(id) ON DELETE CASCADE,
        INDEX idx_job_seeker_educations_profile (job_seeker_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS job_seeker_certifications (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        job_seeker_id BIGINT UNSIGNED NOT NULL,
        name VARCHAR(180) NOT NULL,
        issuer VARCHAR(180) NULL,
        issue_date DATE NULL,
        expiry_date DATE NULL,
        file_path VARCHAR(255) NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_job_seeker_certifications_profile FOREIGN KEY (job_seeker_id) REFERENCES job_seeker_profiles(id) ON DELETE CASCADE,
        INDEX idx_job_seeker_certifications_profile (job_seeker_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS job_seeker_documents (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        job_seeker_id BIGINT UNSIGNED NOT NULL,
        document_type VARCHAR(100) NOT NULL,
        file_path VARCHAR(255) NOT NULL,
        status ENUM("pending", "approved", "rejected") NOT NULL DEFAULT "pending",
        reviewed_by BIGINT UNSIGNED NULL,
        reviewed_at TIMESTAMP NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_job_seeker_documents_profile FOREIGN KEY (job_seeker_id) REFERENCES job_seeker_profiles(id) ON DELETE CASCADE,
        CONSTRAINT fk_job_seeker_documents_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
        INDEX idx_job_seeker_documents_profile (job_seeker_id),
        INDEX idx_job_seeker_documents_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS guarantors (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        job_seeker_id BIGINT UNSIGNED NOT NULL,
        full_name VARCHAR(180) NOT NULL,
        phone VARCHAR(30) NOT NULL,
        email VARCHAR(255) NULL,
        relationship VARCHAR(80) NULL,
        address TEXT NULL,
        occupation VARCHAR(150) NULL,
        document_path VARCHAR(255) NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_guarantors_profile FOREIGN KEY (job_seeker_id) REFERENCES job_seeker_profiles(id) ON DELETE CASCADE,
        INDEX idx_guarantors_profile (job_seeker_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
];
