<?php

declare(strict_types=1);

return [
    'CREATE TABLE IF NOT EXISTS jobs (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        uuid CHAR(36) NOT NULL UNIQUE,
        recruiter_id BIGINT UNSIGNED NOT NULL,
        created_by BIGINT UNSIGNED NOT NULL,
        assigned_hr_officer_id BIGINT UNSIGNED NULL,
        assigned_relationship_officer_id BIGINT UNSIGNED NULL,
        title VARCHAR(180) NOT NULL,
        slug VARCHAR(220) NOT NULL UNIQUE,
        description TEXT NOT NULL,
        requirements TEXT NULL,
        responsibilities TEXT NULL,
        location VARCHAR(150) NOT NULL,
        employment_type VARCHAR(80) NOT NULL,
        work_mode VARCHAR(80) NOT NULL,
        salary_min DECIMAL(14,2) NULL,
        salary_max DECIMAL(14,2) NULL,
        currency CHAR(3) NOT NULL DEFAULT "NGN",
        experience_level VARCHAR(80) NULL,
        application_deadline DATE NULL,
        status ENUM("draft", "pending_approval", "published", "open", "assigned", "paused", "closed", "cancelled", "filled") NOT NULL DEFAULT "draft",
        published_at TIMESTAMP NULL,
        closed_at TIMESTAMP NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        deleted_at TIMESTAMP NULL,
        CONSTRAINT fk_jobs_recruiter FOREIGN KEY (recruiter_id) REFERENCES recruiter_profiles(id) ON DELETE RESTRICT,
        CONSTRAINT fk_jobs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
        CONSTRAINT fk_jobs_hr_officer FOREIGN KEY (assigned_hr_officer_id) REFERENCES users(id) ON DELETE SET NULL,
        CONSTRAINT fk_jobs_relationship_officer FOREIGN KEY (assigned_relationship_officer_id) REFERENCES users(id) ON DELETE SET NULL,
        INDEX idx_jobs_recruiter_id (recruiter_id),
        INDEX idx_jobs_status (status),
        INDEX idx_jobs_slug (slug),
        INDEX idx_jobs_location (location),
        INDEX idx_jobs_assigned_hr (assigned_hr_officer_id),
        INDEX idx_jobs_assigned_relationship (assigned_relationship_officer_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS job_skills (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        job_id BIGINT UNSIGNED NOT NULL,
        skill_name VARCHAR(120) NOT NULL,
        required_level VARCHAR(80) NULL,
        created_at TIMESTAMP NULL,
        CONSTRAINT fk_job_skills_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
        INDEX idx_job_skills_job_id (job_id),
        INDEX idx_job_skills_skill_name (skill_name)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS job_assignments (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        job_id BIGINT UNSIGNED NOT NULL,
        assigned_to_user_id BIGINT UNSIGNED NOT NULL,
        assigned_by_user_id BIGINT UNSIGNED NOT NULL,
        assignment_type ENUM("hr_officer", "relationship_officer") NOT NULL,
        status ENUM("active", "inactive") NOT NULL DEFAULT "active",
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_job_assignments_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
        CONSTRAINT fk_job_assignments_assigned_to FOREIGN KEY (assigned_to_user_id) REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT fk_job_assignments_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
        INDEX idx_job_assignments_job_id (job_id),
        INDEX idx_job_assignments_assigned_to (assigned_to_user_id),
        INDEX idx_job_assignments_type (assignment_type)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
];
