<?php

declare(strict_types=1);

return [
    'CREATE TABLE IF NOT EXISTS assessments (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        title VARCHAR(160) NOT NULL,
        description TEXT NULL,
        assessment_type VARCHAR(80) NOT NULL DEFAULT "general",
        duration_minutes INT UNSIGNED NOT NULL,
        pass_mark DECIMAL(5,2) NOT NULL DEFAULT 50.00,
        created_by BIGINT UNSIGNED NOT NULL,
        status VARCHAR(80) NOT NULL DEFAULT "draft",
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_assessments_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
        INDEX idx_assessments_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS assessment_questions (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        assessment_id BIGINT UNSIGNED NOT NULL,
        question_text TEXT NOT NULL,
        question_type ENUM("multiple_choice", "essay") NOT NULL,
        options_json JSON NULL,
        correct_answer_json JSON NULL,
        score DECIMAL(8,2) NOT NULL DEFAULT 1.00,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_assessment_questions_assessment FOREIGN KEY (assessment_id) REFERENCES assessments(id) ON DELETE CASCADE,
        INDEX idx_assessment_questions_assessment (assessment_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS assessment_assignments (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        assessment_id BIGINT UNSIGNED NOT NULL,
        job_seeker_id BIGINT UNSIGNED NOT NULL,
        job_id BIGINT UNSIGNED NULL,
        application_id BIGINT UNSIGNED NULL,
        assigned_by BIGINT UNSIGNED NOT NULL,
        status VARCHAR(80) NOT NULL DEFAULT "assigned",
        due_date DATE NULL,
        started_at TIMESTAMP NULL,
        submitted_at TIMESTAMP NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_assessment_assignments_assessment FOREIGN KEY (assessment_id) REFERENCES assessments(id) ON DELETE CASCADE,
        CONSTRAINT fk_assessment_assignments_profile FOREIGN KEY (job_seeker_id) REFERENCES job_seeker_profiles(id) ON DELETE CASCADE,
        CONSTRAINT fk_assessment_assignments_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE SET NULL,
        CONSTRAINT fk_assessment_assignments_application FOREIGN KEY (application_id) REFERENCES job_applications(id) ON DELETE SET NULL,
        CONSTRAINT fk_assessment_assignments_user FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE RESTRICT,
        UNIQUE KEY uq_assessment_assignments_once (assessment_id, job_seeker_id, job_id),
        INDEX idx_assessment_assignments_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS assessment_answers (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        assignment_id BIGINT UNSIGNED NOT NULL,
        question_id BIGINT UNSIGNED NOT NULL,
        answer_json JSON NOT NULL,
        score_awarded DECIMAL(8,2) NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_assessment_answers_assignment FOREIGN KEY (assignment_id) REFERENCES assessment_assignments(id) ON DELETE CASCADE,
        CONSTRAINT fk_assessment_answers_question FOREIGN KEY (question_id) REFERENCES assessment_questions(id) ON DELETE CASCADE,
        UNIQUE KEY uq_assessment_answers_question (assignment_id, question_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS assessment_results (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        assignment_id BIGINT UNSIGNED NOT NULL UNIQUE,
        total_score DECIMAL(10,2) NOT NULL DEFAULT 0,
        percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
        status VARCHAR(80) NOT NULL,
        graded_by BIGINT UNSIGNED NULL,
        graded_at TIMESTAMP NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_assessment_results_assignment FOREIGN KEY (assignment_id) REFERENCES assessment_assignments(id) ON DELETE CASCADE,
        CONSTRAINT fk_assessment_results_user FOREIGN KEY (graded_by) REFERENCES users(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS interviews (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        job_id BIGINT UNSIGNED NOT NULL,
        application_id BIGINT UNSIGNED NOT NULL,
        job_seeker_id BIGINT UNSIGNED NOT NULL,
        recruiter_id BIGINT UNSIGNED NOT NULL,
        scheduled_by BIGINT UNSIGNED NOT NULL,
        interview_type ENUM("video", "phone", "physical") NOT NULL,
        meeting_link VARCHAR(500) NULL,
        scheduled_at DATETIME NOT NULL,
        duration_minutes INT UNSIGNED NOT NULL DEFAULT 60,
        status VARCHAR(80) NOT NULL DEFAULT "scheduled",
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_interviews_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
        CONSTRAINT fk_interviews_application FOREIGN KEY (application_id) REFERENCES job_applications(id) ON DELETE CASCADE,
        CONSTRAINT fk_interviews_profile FOREIGN KEY (job_seeker_id) REFERENCES job_seeker_profiles(id) ON DELETE CASCADE,
        CONSTRAINT fk_interviews_recruiter FOREIGN KEY (recruiter_id) REFERENCES recruiter_profiles(id) ON DELETE CASCADE,
        CONSTRAINT fk_interviews_user FOREIGN KEY (scheduled_by) REFERENCES users(id) ON DELETE RESTRICT,
        INDEX idx_interviews_application (application_id),
        INDEX idx_interviews_status (status),
        INDEX idx_interviews_scheduled_at (scheduled_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS interview_feedback (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        interview_id BIGINT UNSIGNED NOT NULL,
        submitted_by BIGINT UNSIGNED NOT NULL,
        rating TINYINT UNSIGNED NULL,
        feedback TEXT NOT NULL,
        recommendation VARCHAR(80) NOT NULL,
        created_at TIMESTAMP NULL,
        updated_at TIMESTAMP NULL,
        CONSTRAINT fk_interview_feedback_interview FOREIGN KEY (interview_id) REFERENCES interviews(id) ON DELETE CASCADE,
        CONSTRAINT fk_interview_feedback_user FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE RESTRICT,
        INDEX idx_interview_feedback_interview (interview_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
];
